"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { EditIcon } from "@/components/icons";
import { displaySerial, normaliseSerial } from "@/lib/normalise";
import { getSupabaseBrowser } from "@/lib/supabase-browser";
import type { Asset, AssetLocation } from "@/lib/types";

export default function EditAssetPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter();
  const [asset, setAsset] = useState<Asset | null>(null); const [locations, setLocations] = useState<AssetLocation[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { void (async () => { const supabase = getSupabaseBrowser(); const [assetResponse, locationResponse] = await Promise.all([supabase.from("assets").select("*").eq("id", id).single(), supabase.from("asset_locations").select("*").order("name")]); if (assetResponse.error) setError(assetResponse.error.message); else setAsset(assetResponse.data as Asset); if (locationResponse.data) setLocations(locationResponse.data as AssetLocation[]); setLoading(false); })(); }, [id]);
  function update(key: keyof Asset, value: unknown) { setAsset((current) => current ? { ...current, [key]: value } : current); }
  async function save(event: FormEvent) { event.preventDefault(); if (!asset) return; setSaving(true); setError(""); const location = locations.find((item) => item.name === asset.storage_location); const { error: updateError } = await getSupabaseBrowser().from("assets").update({ make: asset.make.trim(), model: asset.model.trim(), category: asset.category.trim(), serial_original: displaySerial(asset.serial_original), serial_normalized: normaliseSerial(asset.serial_original), secondary_identifier: asset.secondary_identifier || null, colour: asset.colour || null, storage_location: asset.storage_location || null, location_id: location?.id ?? null, estimated_value: asset.estimated_value || null, supplier: asset.supplier || null, purchase_date: asset.purchase_date || null, purchase_price: asset.purchase_price || null, invoice_number: asset.invoice_number || null, security_id: asset.security_id || null, notes: asset.notes || null }).eq("id", asset.id); if (updateError) { setError(updateError.message); setSaving(false); } else router.push(`/asset/${asset.id}`); }
  if (loading) return <div className="pageWidth pagePad"><div className="skeletonCard" /></div>; if (!asset) return <div className="pageWidth pagePad narrowPage"><div className="notice danger">{error || "Asset not found."}</div></div>;
  return <div className="pageWidth pagePad narrowPage"><Link className="backLink" href={`/asset/${asset.id}`}>← Asset details</Link><div className="sectionTitleRow"><div><p className="eyebrow red">Asset record</p><h1>Edit {asset.make} {asset.model}</h1></div><EditIcon /></div><form className="registrationCard formStack" onSubmit={save}><div className="formGrid two"><label>Make<input value={asset.make} onChange={(event) => update("make", event.target.value)} required /></label><label>Model<input value={asset.model} onChange={(event) => update("model", event.target.value)} required /></label></div><label>Category<input value={asset.category} onChange={(event) => update("category", event.target.value)} required /></label><label>Serial number<input value={asset.serial_original} onChange={(event) => update("serial_original", event.target.value)} required /></label><div className="formGrid two"><label>Colour<input value={asset.colour ?? ""} onChange={(event) => update("colour", event.target.value)} /></label><label>Storage location<input list="saved-locations" value={asset.storage_location ?? ""} onChange={(event) => update("storage_location", event.target.value)} /><datalist id="saved-locations">{locations.map((location) => <option value={location.name} key={location.id} />)}</datalist></label></div><div className="formGrid two"><label>Estimated value (€)<input type="number" step="0.01" value={asset.estimated_value ?? ""} onChange={(event) => update("estimated_value", event.target.value ? Number(event.target.value) : null)} /></label><label>Supplier<input value={asset.supplier ?? ""} onChange={(event) => update("supplier", event.target.value)} /></label></div><div className="formGrid two"><label>Purchase date<input type="date" value={asset.purchase_date ?? ""} onChange={(event) => update("purchase_date", event.target.value)} /></label><label>Purchase price (€)<input type="number" step="0.01" value={asset.purchase_price ?? ""} onChange={(event) => update("purchase_price", event.target.value ? Number(event.target.value) : null)} /></label></div><label>Invoice number<input value={asset.invoice_number ?? ""} onChange={(event) => update("invoice_number", event.target.value)} /></label><label>Notes<textarea rows={4} value={asset.notes ?? ""} onChange={(event) => update("notes", event.target.value)} /></label>{error && <div className="notice danger">{error}</div>}<div className="formActions"><Link className="button secondary" href={`/asset/${asset.id}`}>Cancel</Link><button className="button primary" disabled={saving}>{saving ? "Saving…" : "Save changes"}</button></div></form></div>;
}
