"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import type { User } from "@supabase/supabase-js";
import { AlertIcon,DownloadIcon,EditIcon,PlusIcon,SearchIcon,ToolboxIcon,UploadIcon } from "@/components/icons";
import { csvEscape,downloadTextFile } from "@/lib/csv";
import { getPlan } from "@/lib/plans";
import { getSupabaseBrowser,isSupabaseConfigured } from "@/lib/supabase-browser";
import type { Asset,AssetLocation,Profile } from "@/lib/types";
const defaults=["Drill / driver","Impact driver","Rotary hammer","Angle grinder","Circular saw","Cut-off saw / consaw","Hand tools","Test equipment","Lawn mower","Chainsaw","Site equipment","Plant / machinery","Tool storage","Other"];
export default function AssetsPage(){
 const [user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile|null>(null),[assets,setAssets]=useState<Asset[]>([]),[locations,setLocations]=useState<AssetLocation[]>([]); const [loading,setLoading]=useState(true),[query,setQuery]=useState(""),[filter,setFilter]=useState<"all"|"safe"|"stolen"|"recovered">("all"),[error,setError]=useState(""),[message,setMessage]=useState(""); const [bulk,setBulk]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[field,setField]=useState<"status"|"category"|"storage_location">("storage_location"),[value,setValue]=useState(""),[saving,setSaving]=useState(false);
 async function load(){if(!isSupabaseConfigured()){setError("Supabase is not configured.");setLoading(false);return;}const s=getSupabaseBrowser(),{data:auth}=await s.auth.getUser();setUser(auth.user);if(!auth.user){setLoading(false);return;}const [a,p,l]=await Promise.all([s.from("assets").select("*").order("registered_at",{ascending:false}),s.from("profiles").select("*").eq("id",auth.user.id).maybeSingle(),s.from("asset_locations").select("*").order("name")]);if(a.error)setError(a.error.message);else setAssets((a.data??[]) as Asset[]);if(p.data)setProfile(p.data as Profile);if(l.data)setLocations(l.data as AssetLocation[]);setLoading(false)} useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>assets.filter(a=>(filter==="all"||a.status===filter)&&`${a.make} ${a.model} ${a.serial_original} ${a.category} ${a.storage_location??""}`.toLowerCase().includes(query.toLowerCase())),[assets,filter,query]); const plan=getPlan(profile?.plan_tier); const canBulk=plan.bulkTools;
 function toggle(id:string){setSelected(c=>{const n=new Set(c);n.has(id)?n.delete(id):n.add(id);return n})} function all(){setSelected(c=>c.size===filtered.length?new Set():new Set(filtered.map(a=>a.id)))}
 async function apply(){if(!selected.size||!value.trim()||!confirm(`Update ${selected.size} selected assets?`))return;setSaving(true);setError("");const payload=field==="status"?{status:value}:field==="category"?{category:value.trim()}:{storage_location:value.trim(),location_id:locations.find(l=>l.name===value)?.id??null};const {error:e}=await getSupabaseBrowser().from("assets").update(payload).in("id",[...selected]);if(e)setError(e.message);else{setMessage(`${selected.size} assets updated.`);setSelected(new Set());setValue("");await load()}setSaving(false)}
 function exportCsv(){const h=["make","model","category","serial","status","storage_location","estimated_value","supplier","purchase_date","purchase_price","invoice_number","registered_at"];const lines=[h.join(","),...filtered.map(a=>[a.make,a.model,a.category,a.serial_original,a.status,a.storage_location,a.estimated_value,a.supplier,a.purchase_date,a.purchase_price,a.invoice_number,a.registered_at].map(csvEscape).join(","))];downloadTextFile(`tooltrack-assets-${new Date().toISOString().slice(0,10)}.csv`,lines.join("\n"))}
 if(loading)return <div className="pageWidth pagePad"><div className="skeletonCard"/></div>; if(!user)return <div className="pageWidth pagePad narrowPage"><div className="emptyPanel"><ToolboxIcon/><h1>Sign in to view your assets</h1><Link className="button primary" href="/login?next=/assets">Sign in</Link></div></div>;
 const cats=[...new Set([...defaults,...assets.map(a=>a.category)])].sort(),locs=[...new Set([...locations.map(l=>l.name),...assets.map(a=>a.storage_location).filter(Boolean) as string[]])].sort();
 return <div className="pageWidth pagePad assetsPage"><div className="sectionTitleRow"><div><p className="eyebrow red">Asset register</p><h1>My assets</h1><p className="muted">Search, edit, export and manage your registered equipment.</p></div><div className="headingActions"><Link className="button secondary" href="/import"><UploadIcon/> Import CSV</Link><Link className="button primary" href="/register"><PlusIcon/> Add asset</Link></div></div>{message&&<div className="notice success">{message}</div>}{error&&<div className="notice danger">{error}</div>}
 <div className="assetToolbar"><div className="inputWithIcon"><SearchIcon/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search make, model, serial or location"/></div><div className="pills"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>All</button><button className={filter==="safe"?"active":""} onClick={()=>setFilter("safe")}>Safe</button><button className={filter==="stolen"?"active":""} onClick={()=>setFilter("stolen")}>Stolen</button><button className={filter==="recovered"?"active":""} onClick={()=>setFilter("recovered")}>Recovered</button></div><button className={`button ${bulk?"primary":"secondary"}`} onClick={()=>{setBulk(v=>!v);setSelected(new Set())}}><EditIcon/> {bulk?"Done":"Bulk edit"}</button><button className="button secondary" onClick={exportCsv}><DownloadIcon/> Export</button></div>
 {bulk&&<div className="bulkPanel">{!canBulk?<div className="bulkLocked"><strong>Bulk edit is included with Trade, Business and Fleet accounts.</strong><Link href="/account#plan">View plans</Link></div>:<><div className="bulkSummary"><label className="checkRow compact"><input type="checkbox" checked={filtered.length>0&&selected.size===filtered.length} onChange={all}/><span>Select all visible</span></label><strong>{selected.size} selected</strong></div><div className="bulkControls"><select value={field} onChange={e=>{setField(e.target.value as typeof field);setValue("")}}><option value="storage_location">Storage location</option><option value="category">Category</option><option value="status">Status</option></select>{field==="status"?<select value={value} onChange={e=>setValue(e.target.value)}><option value="">Choose status</option><option value="safe">Safe</option><option value="stolen">Stolen</option><option value="recovered">Recovered</option><option value="transfer">Transfer pending</option></select>:<><input list={field==="category"?"bulk-categories":"bulk-locations"} value={value} onChange={e=>setValue(e.target.value)} placeholder="Choose or type a value"/><datalist id="bulk-categories">{cats.map(v=><option value={v} key={v}/>)}</datalist><datalist id="bulk-locations">{locs.map(v=><option value={v} key={v}/>)}</datalist></>}<button className="button primary" disabled={!selected.size||!value.trim()||saving} onClick={()=>void apply()}>{saving?"Updating…":"Apply"}</button></div></>}</div>}
 {filtered.length?<div className="assetGrid">{filtered.map(a=><article className={`assetCard assetCardV4 ${selected.has(a.id)?"selected":""}`} key={a.id}>{bulk&&canBulk&&<label className="assetSelect"><input type="checkbox" checked={selected.has(a.id)} onChange={()=>toggle(a.id)}/></label>}<Link href={`/asset/${a.id}`} className="assetCardLink"><div className="assetIcon"><ToolboxIcon/></div><div className="assetMain"><div className="assetTop"><h3>{a.make} {a.model}</h3><span className={`status ${a.status}`}>{a.status}</span></div><p>{a.category}</p><dl><div><dt>Serial</dt><dd>{a.serial_original}</dd></div><div><dt>Location</dt><dd>{a.storage_location||"Not set"}</dd></div></dl></div>{a.status==="stolen"&&<AlertIcon className="assetAlert"/>}</Link></article>)}</div>:<div className="emptyPanel"><ToolboxIcon/><h2>{assets.length?"No matching assets":"No assets registered yet"}</h2><Link className="button primary" href="/register">Register an asset</Link></div>}
 </div>
}
