"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { AlertIcon, MapPinIcon, PlusIcon, ShopIcon, ToolboxIcon, UserIcon, UsersIcon } from "@/components/icons";
import { getPlan } from "@/lib/plans";
import { getSupabaseBrowser, isSupabaseConfigured } from "@/lib/supabase-browser";
import type { Asset, Profile, Sighting } from "@/lib/types";

export default function DashboardPage(){
  const [user,setUser]=useState<User|null>(null); const [profile,setProfile]=useState<Profile|null>(null); const [assets,setAssets]=useState<Asset[]>([]); const [sightings,setSightings]=useState<Sighting[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  async function load(){ if(!isSupabaseConfigured()){setError("Supabase is not configured.");setLoading(false);return;} const s=getSupabaseBrowser(); const {data:auth}=await s.auth.getUser(); setUser(auth.user); if(!auth.user){setLoading(false);return;} const [p,a,si]=await Promise.all([s.from("profiles").select("*").eq("id",auth.user.id).maybeSingle(),s.from("assets").select("*").order("registered_at",{ascending:false}),s.from("sightings").select("id, asset_id, theft_report_id, reporter_email, location_area, listing_url, details, status, notification_status, notification_sent_at, created_at, assets(make, model, serial_original)").order("created_at",{ascending:false})]); if(p.data)setProfile(p.data as Profile); if(a.error)setError(a.error.message); else setAssets((a.data??[]) as Asset[]); if(si.data)setSightings(si.data as unknown as Sighting[]); setLoading(false); }
  useEffect(()=>{void load();},[]);
  const greeting=useMemo(()=>{const n=profile?.display_name?.trim()||String(user?.user_metadata?.full_name||"").trim(); if(n)return n.split(/\s+/)[0]; const e=user?.email?.split("@")[0]||"there"; return e.charAt(0).toUpperCase()+e.slice(1);},[profile,user]);
  if(loading)return <div className="pageWidth pagePad"><div className="skeletonCard"/></div>;
  if(!user)return <div className="pageWidth pagePad narrowPage"><div className="emptyPanel"><ToolboxIcon/><h1>Sign in to view your dashboard</h1><Link className="button primary" href="/login">Sign in</Link></div></div>;
  const plan=getPlan(profile?.plan_tier); const newSightings=sightings.filter(x=>x.status==="new"); const recentAssets=assets.slice(0,3); const value=assets.reduce((sum,a)=>sum+Number(a.estimated_value??0),0);
  return <div className="pageWidth pagePad cleanDashboard">
    <div className="sectionTitleRow dashboardHeading"><div><p className="eyebrow red">{plan.name} account</p><h1>Hello, {greeting}</h1><p className="muted">Your tools, alerts and quick actions.</p></div><div className="headingActions"><Link className="button secondary" href="/account"><UserIcon/> Account</Link><Link className="button primary" href="/register"><PlusIcon/> Add asset</Link></div></div>
    {error&&<div className="notice danger">{error}</div>}
    <section className="summaryStrip"><div><span>Assets</span><strong>{assets.length}</strong></div><div><span>Stolen</span><strong className={assets.some(a=>a.status==="stolen")?"redText":""}>{assets.filter(a=>a.status==="stolen").length}</strong></div><div><span>Estimated value</span><strong>€{value.toLocaleString("en-IE",{maximumFractionDigits:0})}</strong></div><Link href="/account#plan">{assets.length} / {plan.assetLimit.toLocaleString()} on {plan.name}</Link></section>
    <section className="cleanSection"><div className="cleanSectionHeader"><div><h2>Quick actions</h2><p>Go straight to the job you need.</p></div></div><div className="cleanActionGrid"><Link href="/assets"><ToolboxIcon/><span><strong>My assets</strong><small>Search, edit and bulk manage</small></span></Link><Link href="/locations"><MapPinIcon/><span><strong>Locations</strong><small>Vans, sheds and sites</small></span></Link><Link href="/team"><UsersIcon/><span><strong>Team</strong><small>Invites and permissions</small></span></Link><Link href="/account/orders"><ShopIcon/><span><strong>My orders</strong><small>View shop order history</small></span></Link></div></section>
    {newSightings.length>0&&<section className="cleanSection"><div className="cleanSectionHeader"><div><h2>New sightings</h2><p>Reports that still need your attention.</p></div><Link href="/sightings">View all</Link></div><div className="compactList">{newSightings.slice(0,3).map(s=><Link href="/sightings" className="compactRow alertRow" key={s.id}><AlertIcon/><div><strong>{s.assets?.make} {s.assets?.model}</strong><span>{s.location_area} · {new Date(s.created_at).toLocaleDateString("en-IE")}</span></div><span className="status stolen">New</span></Link>)}</div></section>}
    <section className="cleanSection"><div className="cleanSectionHeader"><div><h2>Recent assets</h2><p>Your latest registrations.</p></div><Link href="/assets">View all assets</Link></div>{recentAssets.length?<div className="compactList">{recentAssets.map(a=><Link href={`/asset/${a.id}`} className="compactRow" key={a.id}><ToolboxIcon/><div><strong>{a.make} {a.model}</strong><span>Serial {a.serial_original} · {a.storage_location||"No location"}</span></div><span className={`status ${a.status}`}>{a.status}</span></Link>)}</div>:<div className="emptyPanel compactEmpty"><ToolboxIcon/><h2>No assets yet</h2><Link className="button primary" href="/register">Register the first asset</Link></div>}</section>
  </div>;
}
